#!/usr/bin/env bash
set -e # halt script on error

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

title "Building Site"
bundle install
bundle exec jekyll build --drafts

title "Validating Markdown"
bundle exec mdl -c ./.mdlrc _posts

title "Validating HTML"
bundle exec htmlproofer ./_site --check-html --check-favicon --disable-external

# DISABLED: Due to not using custom URL
# title "Checking GitHub Pages is Healthy"
# bundle exec github-pages health-check

title "Cleaning Up"
rm -Rf _site
