#!/usr/bin/env bash
set -e # halt script on error

DATE=`date +%Y-%m-%d`
TITLE=`echo $@`
POSTNAME=`echo $@ | sed -e "s/[[:space:]]/\-/g" | tr '[:upper:]' '[:lower:]'`
FILENAME=_posts/$DATE-$POSTNAME.md

echo "- Creating $FILENAME"
touch $FILENAME

echo "- Adding standard text"
echo "---" > $FILENAME
echo "layout: post" >> $FILENAME
echo "title: $TITLE" >> $FILENAME
echo "description: 'Foo bar baz.'" >> $FILENAME
echo "---" >> $FILENAME
echo "" >> $FILENAME
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." >> $FILENAME
echo "- Opening $FILENAME in Atom"
atom $FILENAME
